a few updates to battery binary. calc to mAh and improve output for future use in xmobar, like sending extra output to stderr and xmobar output to stdout

diff --git a/bin/bin/battery b/bin/bin/battery
--- a/bin/bin/battery
+++ b/bin/bin/battery
@@ -7,60 +7,79 @@ set -u           # disallow unset variables
 # if battery current is higher than this many milliamps, consider it discharging
 DISCHARGE_MODE_THRESHOLD_MA=5
 
+
+echo 'a' >&2
 battery_charge_percent=$(< /sys/class/power_supply/BAT0/capacity)
 
+
+echo 'a VVV below fails sometimes "no such file or something"' >&2
 battery_current_ua=$(< /sys/class/power_supply/BAT0/current_now)
 battery_current_ma=$(echo "$battery_current_ua / 1000" | bc)
 
-battery_charge_now=$(< /sys/class/power_supply/BAT0/charge_now)
-battery_charge_full=$(< /sys/class/power_supply/BAT0/charge_full)
-battery_charge_full_design=$(< /sys/class/power_supply/BAT0/charge_full_design)
-battery_health_percent=$(echo "100.0 * $battery_charge_full / $battery_charge_full_design" | bc)
+battery_charge_now_uah=$(< /sys/class/power_supply/BAT0/charge_now)
+battery_charge_now_mah=$(echo "$battery_charge_now_uah / 1000" | bc)
+
+battery_charge_full_uah=$(< /sys/class/power_supply/BAT0/charge_full)
+battery_charge_full_mah=$(echo "$battery_charge_full_uah / 1000" | bc)
+
+battery_charge_full_design_uah=$(< /sys/class/power_supply/BAT0/charge_full_design)
+battery_charge_full_design_mah=$(echo "$battery_charge_full_design_uah / 1000" | bc)
+
+battery_health_percent=$(echo "100.0 * $battery_charge_full_mah / $battery_charge_full_design_mah" | bc)
 
 battery_status=$(< /sys/class/power_supply/BAT0/status)
 
 battery_brand=$(< /sys/class/power_supply/BAT0/manufacturer)
 battery_model=$(< /sys/class/power_supply/BAT0/model_name)
 
-# call acpi | look for "HH:MM:SS remaining" | keep text before space | trim whitespace
-battery_time_left=$(acpi -b | egrep -o "[0-9:]+ remaining" | cut -d " " -f 1 | awk '{$1=$1};1')
+# call acpi | look for "HH:MM:SS remaining" and ignore failures | keep text before space | trim whitespace
+battery_time_left=$(acpi -b | egrep -o "[0-9:]+ remaining" || true | cut -d " " -f 1 | awk '{$1=$1};1')
 
 if [ "$battery_time_left" != "" ]; then
-    battery_time_left_string=$(echo ", $battery_time_left left")
+    #battery_time_left_string=$(echo ", $battery_time_left left")
+    battery_time_left_string=$(echo " $battery_time_left")
 else
-    batterry_time_left_string=""
+    battery_time_left_string=""
 fi
 
-if $(type tlp-stat >&- 2>&-); then
+if command -v tlp-stat > /dev/null; then
     # call tlp-stat | keep only Mode= line | keep text after = | trim whitespace
     tlp_power_mode=$(tlp-stat -s | egrep "Mode\W+= " | cut -d "=" -f 2 | awk '{$1=$1};1')
 else
     tlp_power_mode="TLP Not Installed"
 fi
 
-echo "Battery brand: $battery_brand  model: $battery_model"
-echo "Battery at $battery_charge_percent%"
-echo "Battery draw: $battery_current_ma mA"
-echo "Battery health: $battery_charge_full / $battery_charge_full_design ($battery_health_percent%)"
-echo "Battery Status: $battery_status"
-echo "TLP Power Mode: $tlp_power_mode"
+echo "Battery brand: $battery_brand  model: $battery_model" >&2
+echo "Battery at $battery_charge_percent%" >&2
+echo "Battery draw: $battery_current_ma mA" >&2
+echo "Battery health: $battery_charge_full_mah mAh / $battery_charge_full_design_mah mAh ($battery_health_percent%)" >&2
+echo "Battery status: $battery_status" >&2
+echo "TLP power mode: $tlp_power_mode" >&2
 
 if [ $battery_current_ma -gt $DISCHARGE_MODE_THRESHOLD_MA ]; then
     # battery current > threshold so charging or discharging
 
     case $battery_status in
     Charging)
-        echo "State: AC_Charging$battery_time_left_string"
+        echo "State: AC_Charging$battery_time_left_string" >&2
+        status_bar_text="<plug_icon> $battery_charge_percent%$battery_time_left_string"
         ;;
     Unknown)
-        echo "State: Discharging$battery_time_left_string"
+        echo "State: Discharging$battery_time_left_string" >&2
+        status_bar_text="<lightning_bolt_icon> $battery_charge_percent%$battery_time_left_string"
         ;;
     *)
-        echo "State: Discharging$battery_time_left_string"
+        echo "State: Discharging$battery_time_left_string" >&2
+        status_bar_text="<lightning_bolt_icon> $battery_charge_percent%$battery_time_left_string"
         ;;
     esac
 
 
 else
-    echo "State: AC_Idle"
+    echo "State: AC_Idle" >&2
+        status_bar_text="<dot_icon> $battery_charge_percent%$battery_time_left_string"
 fi
+
+echo "Status bar:" >&2
+echo "$status_bar_text"
+
